# Generated by Django 3.2.10 on 2024-04-11 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yr_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
