# Generated by Django 3.2.10 on 2025-03-06 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yr_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='product',
            name='updated_at',
        ),
    ]
