# Generated by Django 3.2.10 on 2025-03-11 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yr_app', '0002_pageview_product'),
    ]

    operations = [
    ]
