# Generated by Django 3.2.10 on 2025-03-12 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yr_app', '0003_auto_20250311_2237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='order_count',
        ),
    ]
