# Generated by Django 3.2.10 on 2024-05-27 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yr_app', '0004_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='product',
            name='updated_at',
        ),
    ]
