# Generated by Django 3.2.10 on 2025-03-12 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yr_app', '0005_product_order_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='order_count',
        ),
    ]
